import Head from "next/head";
import {
  Background,
  Banner,
  Footer,
  Header,
  Readourblog,
  Subheading,
  Subheadline,
  Upcomingsermons,
  Watchandlisten,
} from "../Component";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Subheading />
      <Subheadline />
      <Watchandlisten />
      <Upcomingsermons />
      <Background />
      <Readourblog />
      <Footer />
    </div>
  );
}
