import Head from "next/head";
import React from "react";
import { useState } from "react";
import {
  Background,
  Banner,
  Footer,
  Header,
  Readourblog,
  Subheading,
  Subheadline,
  Upcomingsermons,
  Watchandlisten,
  Loader,
} from "../Component";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [toggleMenu, setToggleMenu] = useState(false);
  const OnCange = () => {
    setToggleMenu(true);
    setTimeout(() => {
      setToggleMenu(false);
    }, 3000);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {toggleMenu && (
        <div
          style={{
            zIndex: 999999999999,
            position: "absolute",
            height: "100vh",
            width: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Loader />
        </div>
      )}

      <Header onAboutChange={() => OnCange()} />
      <Banner />
      <Subheading />
      <Subheadline />
      <Watchandlisten />
      <Upcomingsermons />
      <Background />
      <Readourblog />
      <Footer />
    </div>
  );
}
